#index:
#    path: /
#    controller: App\Controller\DefaultController::index

list_users:
  path: /users
  controller: App\Controller\UserController::index
  methods: GET

create_user:
  path: /users
  controller: App\Controller\UserController::create
  methods: POST

update_user:
  path: /users/{id}
  controller: App\Controller\UserController::update
  methods: PUT