#index:
#    path: /
#    controller: App\Controller\DefaultController::index

list_users:
  path: /users
  controller: App\Controller\UserController::index
  methods: GET

find_user:
  path: /users/{id}
  controller: App\Controller\UserController::show
  methods: GET

create_user:
  path: /users
  controller: App\Controller\UserController::create
  methods: POST

update_user:
  path: /users/{id}
  controller: App\Controller\UserController::update
  methods: PUT

#Message Routes

list_messages:
  path: /messages/{chatId}
  controller: App\Controller\MessageController::index
  methods: GET

save_message:
  path: /messages
  controller: App\Controller\MessageController::saveMessage
  methods: POST
