-- MySQL Script generated by MySQL Workbench
-- Mon Feb 14 23:22:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema social-network
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema social-network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social-network` DEFAULT CHARACTER SET utf8 ;
USE `social-network` ;

-- -----------------------------------------------------
-- Table `social-network`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social-network`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `celphone` VARCHAR(11) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `birthday` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `celphone_UNIQUE` (`celphone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social-network`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social-network`.`chats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_sender_id` INT UNSIGNED NOT NULL,
  `user_recipient_id` INT UNSIGNED NOT NULL,
  `has_unverified_message` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_chats_users1_idx` (`user_sender_id` ASC) VISIBLE,
  INDEX `fk_chats_users2_idx` (`user_recipient_id` ASC) VISIBLE,
  CONSTRAINT `fk_chats_users1`
    FOREIGN KEY (`user_sender_id`)
    REFERENCES `social-network`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chats_users2`
    FOREIGN KEY (`user_recipient_id`)
    REFERENCES `social-network`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social-network`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social-network`.`messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `message_send_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_sender_id` INT UNSIGNED NOT NULL,
  `user_recipient_id` INT UNSIGNED NOT NULL,
  `chat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_messages_users_idx` (`user_sender_id` ASC) VISIBLE,
  INDEX `fk_messages_users1_idx` (`user_recipient_id` ASC) VISIBLE,
  INDEX `fk_messages_chats1_idx` (`chat_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`user_sender_id`)
    REFERENCES `social-network`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`user_recipient_id`)
    REFERENCES `social-network`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_chats1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `social-network`.`chats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
